### ISSUE TITLE
Why not merging with SimpleFinance/chef-influxdb ?

### ISSUE THREAD

**Issue by BarthV** [zeroXten/influxdb-chef#7]
Hi,

Did you realized that a more solid influxdb cookbook was already available before putting this on supermarket ?

 https://github.com/SimpleFinance/chef-influxdb

To help curing the "yet-antoher-cookbook" syndrom and fighting cookbook inflation, can you think about deprecate this one or merging with it ?

Thanks for all.

**Comment by zeroXten** [comment]
I'd be happy to deprecate, but I created this because there wasn't anything available via Supermarket.

**Comment by BarthV** [comment]
yeah :) i created an issue claiming for a release on supermarket ..
https://github.com/SimpleFinance/chef-influxdb/issues/23

Burt maintainers seems have forgot about my case :'(

I'll bump them asap.

**Comment by zeroXten** [comment]
They have suggested I handle the upload. Basically I would deprecate this code and upload theirs into the existing cookbook the Supermarket. I'll take a look at doing it as some point soon.

**Comment by BarthV** [comment]
Thanks a lot :-)

If you feel the need to, I can also handle the upload job if you're away.
