### ISSUE TITLE
0.9 is out ! Time to refactor :)

### ISSUE THREAD

**Issue by BarthV** [zeroXten/influxdb-chef#9]
Ohai !

0.9 is out !

Maybe we can strengthen this cookbook, review & refactor it and makes it follow all chef industry standard ?
Let's make this cookbook production ready and prepare it o the future N-nodes cluster feature !

Maybe are you already planning something ? If you do, maybe we can team-up and bring some improvements, flexibility and testability to your work ?

Thanks !

**Comment by zeroXten** [comment]
I'll deprecate this one today and will replace the supermarket entry with SimpleFinance's

**Comment by zeroXten** [comment]
Done.
